# Generated by Django 4.1.6 on 2023-03-16 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_paper', '0003_category_subscribers_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 16, 3, 31, 3, 31927, tzinfo=datetime.timezone.utc)),
        ),
    ]
